### ISSUE TITLE
Lookup - Fix Empty Slide Deck & BOM Links

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/PM-Dashboard-v1#165]
Currently, when looking up a project, there will always be a hyperlink for the slide deck link and BOM link even when it is empty in the PM21 spreadsheet. This is not ideal as the user will click on the link expecting to access the slide deck or BOM, while the link will actually bring them to an empty page. An example of this issue would be for the project with the WBS# of 1.7.0.

**Comment by lpfahler16** [comment]
I changed the getHTMLLink method because this seemed to be the cleanest way to do it. I can return "No Link" or something similar instead of an empty string if that is better. A side effect of this change is it actually fixed a similar problem on the project page because it also uses the getHTMLLink method.
